---
- name: Reset Kubernetes nodes
  hosts: all
  become: yes
  tasks:
    - name: Reset kubeadm
      command: kubeadm reset -f
      changed_when: false
    - name: Remove CNI config
      file:
        path: /etc/cni/net.d
        state: absent
