---
- name: Upgrade Kubernetes
  hosts: control-plane
  become: yes
  tasks:
    - name: Upgrade packages
      ansible.builtin.package:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: latest
      notify: Restart kubelet
  handlers:
    - name: Restart kubelet
      ansible.builtin.service:
        name: kubelet
        state: restarted
