name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          pip install -r requirements.txt
      - name: Prepare example database
        run: python tools/create_example_db.py
      - name: Prepare files
        run: python tools/generate_files.py --db database/example.db
      - name: Lint
        run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          pip install -r requirements.txt
      - name: Prepare example database
        run: python tools/create_example_db.py
      - name: Prepare files
        run: python tools/generate_files.py --db database/example.db
      - name: Run Molecule tests
        run: make test
  report:
    if: success()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cluster Ready" > report.html
      - uses: actions/upload-artifact@v3
        with:
          name: report
          path: report.html
